name: Build, test and publish
on: [ push ]

jobs:
  build-test-publish:
    name: Build, test and publish
    uses: HavenDV/workflows/dotnet_build-test-publish.yml@master
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}